"""Sync ``docs/plans/PLAN_INDEX.md`` with the per-store frontmatter.

Walks the six Bodai documentation stores that ship
``*.md`` files with YAML frontmatter, parses the canonical fields
(``status``, ``role``, ``date``, ``topic``, ``title``) for each, and
emits a deterministic registry table to
``docs/plans/PLAN_INDEX.md``. Used as a crackerjack fast-hook to
keep the plan index honest whenever plan/decisions/spec files
change; the index itself is regenerated by ``scripts/regenerate_plan_index.py``
in akosha — this tool mirrors that logic but lives in crackerjack's
hooks path so ``crackerjack run`` can run it directly without a
cross-repo import.

Mirrors the akosha canonical:
``akosha/scripts/regenerate_plan_index.py``
:ref:``docs/plans/2026-09-27-pyproject-single-source-of-truth.md``.

CLI::

    python -m crackerjack.tools.plan_index_sync            # rewrite
    python -m crackerjack.tools.plan_index_sync --dry-run   # print diff
"""

from __future__ import annotations

import argparse
import datetime
import os
import re
import sys
from collections import Counter
from dataclasses import dataclass
from pathlib import Path

try:
    import yaml  # PyYAML; bundled with crackerjack's dev group.
except ImportError as exc:  # pragma: no cover - import guard
    sys.stderr.write(
        "PyYAML is required; install with `uv pip install pyyaml`\n"
        f"Original error: {exc}\n"
    )
    raise SystemExit(2) from exc


# ---------------------------------------------------------------------------
# Constants — mirror crackerjack.services.frontmatter where it exists.
# ---------------------------------------------------------------------------

LIFECYCLE_VALUES: tuple[str, ...] = (
    "draft",
    "active",
    "partial",
    "shipped",
    "complete",
)
ROLE_VALUES: tuple[str, ...] = (
    "canonical",
    "implementation",
    "umbrella",
    "historical",
    "superseded",
)

# Stores walked (POSIX, relative to repo root).
DEFAULT_STORES: tuple[str, ...] = (
    "docs/adr/",
    "docs/plans/",
    "docs/superpowers/specs/",
    "docs/superpowers/plans/",
    ".claude/decisions/",
    "docs/followups/",
)

# Frontmatter regex — captures the YAML block between the opening and
# closing `---` fences.
_FRONTMATTER_RE = re.compile(r"\A---\s*\n(.*?)\n---\s*(?:\n|$)", re.DOTALL)


@dataclass(frozen=True)
class Entry:
    """One row in the registry — a file with parsed frontmatter."""

    rel: str
    store: str
    date: str
    status: str
    role: str
    topic: str
    title: str


# ---------------------------------------------------------------------------
# Frontmatter parsing
# ---------------------------------------------------------------------------


def extract_frontmatter(text: str) -> dict[str, object] | None:
    match = _FRONTMATTER_RE.match(text)
    if match is None:
        return None
    parsed = yaml.safe_load(match.group(1))
    if parsed is None:
        return {}
    if not isinstance(parsed, dict):
        return None
    return parsed


def _coerce_date(value: object) -> str:
    """Coerce both ``datetime.date`` and ISO strings to ``YYYY-MM-DD``."""
    if isinstance(value, datetime.date):
        return value.isoformat()
    if isinstance(value, str):
        return value
    return ""


def _coerce_str(value: object | None, fallback: str) -> str:
    """Coerce an unknown ``front.get(...)`` value to ``str`` with fallback.

    Centralises the ``front.get(...) if isinstance(...) else fallback``
    pattern so callers don't rely on type-checkers narrowing
    conditional expressions. The ``front`` mapping from
    :func:`extract_frontmatter` is typed as ``dict[str, object]`` so
    ``.get(k)`` returns ``object | None`` — a conditional expression
    can't be narrowed to ``str`` even with an ``isinstance`` runtime
    check (ty's narrowing rules treat the rhs of a ternary as the
    join of both branches, not a narrowed version), so we route the
    ``isinstance`` check through this explicitly-typed helper.
    """
    return value if isinstance(value, str) else fallback


def _title_from_text(text: str, fallback: str) -> str:
    for line in text.splitlines():
        stripped = line.strip()
        if stripped.startswith("# "):
            return stripped[2:].strip()
    return fallback


def _is_excluded(rel: str) -> bool:
    """Skip the index itself, the drafts subdirectory, and any archive."""
    if rel == "docs/plans/PLAN_INDEX.md":
        return True
    if "docs/plans/drafts/" in rel:
        return True
    parts = rel.split("/")
    return any(p in {"archive", ".archive"} for p in parts)


def _discover_files(repo_root: Path, store_rel: str) -> list[tuple[Path, str]]:
    root = repo_root / store_rel.rstrip("/")
    if not root.is_dir():
        return []
    out: list[tuple[Path, str]] = []
    for path in sorted(root.rglob("*.md")):
        rel = path.relative_to(repo_root).as_posix()
        if _is_excluded(rel):
            continue
        out.append((path, rel))
    return out


def _entry_from_file(abs_path: Path, rel: str, store: str) -> Entry | None:
    """Parse one file. Returns ``None`` when no valid frontmatter."""
    try:
        text = abs_path.read_text(encoding="utf-8")
    except OSError:
        return None
    front = extract_frontmatter(text)
    if front is None:
        return None
    date = _coerce_date(front.get("date"))
    status = _coerce_str(front.get("status"), "unknown")
    role = _coerce_str(front.get("role"), "unknown")
    topic = _coerce_str(front.get("topic"), "—")
    fallback_title = abs_path.stem.replace("-", " ").replace("_", " ")
    title = _title_from_text(text, fallback=fallback_title)
    return Entry(
        rel=rel,
        store=store,
        date=date,
        status=status,
        role=role,
        topic=topic,
        title=title,
    )


# ---------------------------------------------------------------------------
# Rendering
# ---------------------------------------------------------------------------


def _entry_link(rel: str, _store: str) -> str:
    """Render a markdown link from ``docs/plans/PLAN_INDEX.md`` to ``rel``.

    The index file always lives at ``docs/plans/PLAN_INDEX.md``, so the
    link target must be the path of ``rel`` *relative to* that directory.
    We let stdlib compute it instead of hand-rolling prefix branches —
    the previous version assumed PLAN_INDEX.md lived at the repo root,
    producing links that resolved to ``docs/plans/docs/plans/...`` (and
    the equivalent broken paths for ``docs/`` and ``.claude/`` stores).

    Display text stays as the full repo-relative ``rel`` so readers can
    see the absolute-looking path; only the link *target* is shortened.
    """
    target = os.path.relpath(rel, "docs/plans")
    return f"[`{rel}`]({target})"


def _render_store_table(store: str, entries: list[Entry]) -> str:
    label = store.rstrip("/").replace("docs/", "Docs: ").replace(".claude/", ".claude/")
    rows: list[str] = [f"### {label}", ""]
    rows.extend(
        (
            "| Path | Date | Status | Role | Topic | Title |",
            "|---|---|---|---|---|---|",
        )
    )
    if not entries:
        rows.extend(
            (
                "| _no entries with valid frontmatter_ | | | | | |",
                "",
            )
        )
        return "\n".join(rows)
    sorted_entries = sorted(entries, key=lambda e: e.rel)
    for entry in sorted_entries:
        rows.append(
            f"| {_entry_link(entry.rel, entry.store)} "
            f"| {entry.date or '—'} "
            f"| `{entry.status}` "
            f"| `{entry.role}` "
            f"| `{entry.topic}` "
            f"| {entry.title} |"
        )
    rows.append("")
    return "\n".join(rows)


def _render_distribution(entries: list[Entry]) -> str:
    counts: Counter[tuple[str, str]] = Counter()
    for e in entries:
        if "unknown" in (e.status, e.role):
            continue
        counts[(e.status, e.role)] += 1

    rows: list[str] = ["## Lifecycle × Role Distribution", ""]
    header = "| Role \\ Lifecycle | " + " | ".join(LIFECYCLE_VALUES) + " | Total |"
    sep = "|---|" + "|".join(["---"] * (len(LIFECYCLE_VALUES) + 1)) + "|"
    rows.extend((header, sep))

    for role in ROLE_VALUES:
        cells: list[str] = []
        row_total = 0
        for lifecycle in LIFECYCLE_VALUES:
            cell_value = counts.get((lifecycle, role), 0)
            row_total += cell_value
            cells.append(str(cell_value) if cell_value else "·")
        rows.append(f"| `{role}` | " + " | ".join(cells) + f" | **{row_total}** |")

    col_totals: list[str] = []
    for lifecycle in LIFECYCLE_VALUES:
        col_sum = sum(counts.get((lifecycle, role), 0) for role in ROLE_VALUES)
        col_totals.append(str(col_sum) if col_sum else "·")
    grand_total = sum(int(t) if t.isdigit() else 0 for t in col_totals)
    rows.extend(
        (
            "| **Total** | "
            + " | ".join(f"**{t}**" for t in col_totals)
            + f" | **{grand_total}** |",
            "",
        )
    )
    return "\n".join(rows)


def _render_index(entries_by_store: dict[str, list[Entry]], generated_at: str) -> str:
    sections: list[str] = ["# Plan Index", ""]
    sections.extend(
        (
            (
                f"_Regenerated {generated_at} by "
                f"`crackerjack.tools.plan_index_sync` (fast-hook)._"
            ),
            "",
        )
    )

    all_entries: list[Entry] = []
    for store in DEFAULT_STORES:
        store_entries = entries_by_store.get(store, [])
        all_entries.extend(store_entries)
        sections.append(_render_store_table(store, store_entries))

    sections.append(_render_distribution(all_entries))
    return "\n".join(sections) + "\n"


# ---------------------------------------------------------------------------
# Driver
# ---------------------------------------------------------------------------


def render_plan_index(repo_root: Path) -> str:
    """Walk the six stores; return the rendered ``PLAN_INDEX.md`` body."""
    entries_by_store: dict[str, list[Entry]] = {}
    for store in DEFAULT_STORES:
        files = _discover_files(repo_root, store)
        store_entries: list[Entry] = []
        for abs_path, rel in files:
            entry = _entry_from_file(abs_path, rel, store)
            if entry is None:
                continue
            store_entries.append(entry)
        entries_by_store[store] = store_entries
    return _render_index(
        entries_by_store,
        generated_at=datetime.datetime.now(tz=datetime.UTC).date().isoformat(),
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="plan_index_sync",
        description=(
            "Regenerate docs/plans/PLAN_INDEX.md from per-store frontmatter. "
            "Used as a crackerjack fast-hook (plan-index-sync)."
        ),
    )
    parser.add_argument(
        "--repo-root",
        type=Path,
        default=Path(),
        help="Repo root (default: cwd)",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=Path("docs/plans/PLAN_INDEX.md"),
        help="Output path (default: docs/plans/PLAN_INDEX.md)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print whether the index would change without writing",
    )
    args = parser.parse_args(argv)

    new_content = render_plan_index(args.repo_root)

    if args.dry_run:
        existing = args.out.read_text(encoding="utf-8") if args.out.exists() else ""
        if existing == new_content:
            print(f"no change → {args.out}")
            return 0
        print(f"would rewrite {args.out} ({len(existing)} → {len(new_content)} bytes)")
        return 1

    args.out.parent.mkdir(parents=True, exist_ok=True)
    existing = args.out.read_text(encoding="utf-8") if args.out.exists() else ""
    if existing == new_content:
        print(f"up-to-date → {args.out}")
        return 0
    args.out.write_text(new_content, encoding="utf-8")
    print(f"wrote {args.out} ({len(new_content)} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
