TIMEOUT_THRESHOLD_MULTIPLIER = 0.9
MAX_TEST_DURATION_WARNING = 300.0


MAX_TEST_FAILURES_TO_DISPLAY = 50
MAX_TEST_ERRORS_TO_DISPLAY = 100


DEFAULT_PARALLEL_TESTS = 4
MIN_PARALLEL_THRESHOLD = 10


PROGRESS_UPDATE_PERCENTAGE = 5


MAX_AI_FIX_ITERATIONS = 10
MIN_AI_CONFIDENCE_THRESHOLD = 0.7


SLOW_HOOK_THRESHOLD = 5.0
VERY_SLOW_HOOK_THRESHOLD = 30.0


DEFAULT_PYPI_TIMEOUT = 300
DEFAULT_GITHUB_TIMEOUT = 60


PATTERN_CACHE_TTL = 300
INDEX_CACHE_TTL = 600


MAX_WATCHED_FILES = 1000
DEBOUNCE_INTERVAL = 0.5


MAX_CONCURRENT_WORKERS = 8
TASK_DISPATCH_TIMEOUT = 60.0


DEFAULT_PANEL_WIDTH = 80
DEFAULT_COLUMN_WIDTH = 120
