from .bandit import PATTERNS as BANDIT_PATTERNS
from .other import PATTERNS as OTHER_PATTERNS
from .pyright import PATTERNS as PYRIGHT_PATTERNS
from .ruff import PATTERNS as RUFF_PATTERNS

PATTERNS = RUFF_PATTERNS | PYRIGHT_PATTERNS | BANDIT_PATTERNS | OTHER_PATTERNS

__all__ = ["PATTERNS"]
