site_name: Project Documentation
site_description: Comprehensive project documentation
site_author: Crackerjack
theme:
  name: material
  features:
  - navigation.sections
  - navigation.expand
  - navigation.top
  - search.highlight
  - search.share
  palette:
  - scheme: default
    primary: blue
    accent: blue
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  - scheme: slate
    primary: blue
    accent: blue
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
nav:
  Home: index.md
  Getting Started: getting-started.md
  User Guide: user-guide.md
  API Reference: api-reference.md
  Development: development.md
plugins:
- search
- autorefs
- mkdocstrings
markdown_extensions:
- markdown.extensions.toc
- markdown.extensions.tables
- markdown.extensions.fenced_code
- markdown.extensions.codehilite
- markdown.extensions.admonition
- pymdownx.details
- pymdownx.superfences
- pymdownx.highlight
- pymdownx.inlinehilite
- pymdownx.snippets
