from .badges_markdown import PATTERNS as BADGES_MARKDOWN_PATTERNS
from .comments_blocks import PATTERNS as COMMENTS_BLOCKS_PATTERNS
from .docstrings import PATTERNS as DOCSTRINGS_PATTERNS

PATTERNS = DOCSTRINGS_PATTERNS | BADGES_MARKDOWN_PATTERNS | COMMENTS_BLOCKS_PATTERNS

__all__ = ["PATTERNS"]
