DEFAULT_ZUBAN_LSP_TIMEOUT = 120
DEFAULT_GLOBAL_LOCK_TIMEOUT = 1800
DEFAULT_TEST_TIMEOUT = 600
DEFAULT_COMMAND_TIMEOUT = 300


DEFAULT_MAX_AI_ITERATIONS = 10


DEFAULT_COVERAGE_GOAL = 100.0
COVERAGE_RATCHET_THRESHOLD = 0.0


MAX_FILE_SIZE_BYTES = 100_000


MAX_FAILURES_TO_DISPLAY = 10
MAX_ISSUES_TO_DISPLAY = 20


PROGRESS_UPDATE_INTERVAL = 1
PROGRESS_SLOW_UPDATE_INTERVAL = 5


DEFAULT_LSP_PORT = 8677
DEFAULT_LSP_MODE = "tcp"


DEFAULT_XCODE_PROJECT = "app/MdInjectApp/MdInjectApp.xcodeproj"
DEFAULT_XCODE_SCHEME = "MdInjectApp"
DEFAULT_XCODE_CONFIGURATION = "Debug"
DEFAULT_XCODE_DESTINATION = "platform=macOS"


DEFAULT_HEATMAP_TYPE = "error_frequency"
ANOMALY_DETECTION_SENSITIVITY = 2.0
PREDICTION_PERIODS_DEFAULT = 10


TEMP_FILE_EXTENSION = ".tmp"
CACHE_DIR_NAME = ".cache"


DEFAULT_GIT_REMOTE = "origin"
DEFAULT_GIT_BRANCH = "main"


PROJECT_NAME = "crackerjack"
VARIABLE_PREFIX = "CRACKERJACK"
