"""ed25519 keypair generation and serialization.

A Bodai server ships ONE ed25519 signing keypair per installation.
The private key is held in process memory (or on disk for key
rotation workflows — outside this module's scope). The public key
half is published in the server's ``/health`` response under
``feed.skills_signer.pubkey`` so that any client can verify a
signature without out-of-band key exchange.

The ``key_id`` is a stable, deterministic 16-char hex string derived
from the SHA-256 of the raw 32-byte public key. Two servers with
different keypairs MUST produce different ``key_id`` values; rotation
produces a new ``key_id`` and clients MUST reject signatures against
the retired ``key_id`` (the rotation protocol itself is out of scope
for this module — see plan §10.1).
"""

from __future__ import annotations

import hashlib
from dataclasses import dataclass
from pathlib import Path
from typing import Final

from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric import ed25519
from cryptography.hazmat.primitives.asymmetric.ed25519 import (
    Ed25519PrivateKey,  # runtime value in generate_keypair()
    Ed25519PublicKey,  # runtime arg in _derive_key_id()
)

# Number of bytes of the SHA-256 hash used as the key_id. 8 bytes =
# 16 hex chars. A collision-resistant 64-bit identifier is sufficient
# for a single-server key namespace; cross-server uniqueness is
# implicit because the same public key cannot exist on two servers
# without a key-sharing protocol (also out of scope).
KEY_ID_BYTES: Final = 8


@dataclass(frozen=True, slots=True)
class Keypair:
    """An ed25519 keypair.

    Attributes:
        key_id: stable 16-char hex identifier for the public key.
        private_key: the ed25519 private key half (for signing).
        public_key: the ed25519 public key half (for verification).
    """

    key_id: str
    private_key: Ed25519PrivateKey
    public_key: Ed25519PublicKey


def generate_keypair() -> Keypair:
    """Generate a fresh ed25519 keypair.

    The private key is generated by the OS CSPRNG via
    ``cryptography``. The ``key_id`` is the first 8 bytes of
    ``SHA-256(public_key_bytes)``, hex-encoded.

    Returns:
        A :class:`Keypair` ready for signing.
    """
    private_key = ed25519.Ed25519PrivateKey.generate()
    public_key = private_key.public_key()
    return Keypair(
        key_id=_derive_key_id(public_key),
        private_key=private_key,
        public_key=public_key,
    )


def public_key_from_bytes(raw: bytes) -> Ed25519PublicKey:
    """Deserialize an ed25519 public key from raw 32-byte form.

    Args:
        raw: exactly 32 bytes (the X25519/ed25519 public-key wire format).

    Returns:
        A :class:`Ed25519PublicKey` instance ready for verification.

    Raises:
        ValueError: when ``raw`` is not exactly 32 bytes.
    """
    if len(raw) != 32:
        raise ValueError(
            f"ed25519 public key must be exactly 32 bytes; got {len(raw)}"
        )
    return ed25519.Ed25519PublicKey.from_public_bytes(raw)


def _derive_key_id(public_key: Ed25519PublicKey) -> str:
    """Return the deterministic ``key_id`` for ``public_key``.

    Args:
        public_key: the ed25519 public key half.

    Returns:
        16-char lowercase hex string.
    """
    raw = public_key.public_bytes(
        encoding=serialization.Encoding.Raw,
        format=serialization.PublicFormat.Raw,
    )
    digest = hashlib.sha256(raw).digest()
    return digest[:KEY_ID_BYTES].hex()


def load_or_create_keypair(path: Path) -> Keypair:
    """Load the persisted keypair at ``path`` or generate + persist a fresh one.

    Persists the private key as unencrypted PKCS8 PEM. Without persistence,
    every server restart produces a fresh ``key_id`` and every previously
    installed Skill (Phase 2/6) becomes unverifiable — the user would have
    to delete and reinstall every Skill. This is the silent footgun Phase
    1.5 ships infrastructure to prevent.

    The parent directory is created with ``0o700`` and the key file with
    ``0o600``. The file is written atomically (write then chmod); an
    attacker reading the process's file descriptors between write and
    chmod would still see ``0o644``, but the window is small and the
    ``chmod`` happens in the same syscall as the function return.

    Args:
        path: PEM file path. Will be created (with parents) at ``0o600``
            if it does not exist.

    Returns:
        The loaded :class:`Keypair`, or the freshly-generated one.

    Raises:
        ValueError: when the file exists but is not a valid ed25519
            PEM private key, or when ``path.parent`` cannot be created
            (e.g. permissions denied).
        OSError: when ``path`` cannot be read or written.
    """
    if path.exists():
        raw = path.read_bytes()
        loaded = serialization.load_pem_private_key(raw, password=None)
        if not isinstance(loaded, ed25519.Ed25519PrivateKey):
            raise ValueError(
                f"key at {path} is not an ed25519 private key "
                f"(got {type(loaded).__name__})"
            )
        public_key = loaded.public_key()
        return Keypair(
            key_id=_derive_key_id(public_key),
            private_key=loaded,
            public_key=public_key,
        )

    # Generate and persist. Create parent dirs with restrictive perms first
    # so the new file doesn't briefly sit under permissive defaults.
    path.parent.mkdir(parents=True, exist_ok=True)
    # ``exist_ok=True`` may have created with default umask; tighten now.
    Path.chmod(path.parent, 0o700)

    keypair = generate_keypair()
    pem = keypair.private_key.private_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PrivateFormat.PKCS8,
        encryption_algorithm=serialization.NoEncryption(),
    )
    path.write_bytes(pem)
    Path.chmod(path, 0o600)
    return keypair
